import type { EntitlementCache } from '@marginbase/entitlements';

const FREE_EXPORT_WATERMARK = 'Generated by MarginBase';

export const hasPaidEntitlement = (cache: EntitlementCache): boolean => {
  return cache.entitlementSet.bundle || cache.entitlementSet.breakeven || cache.entitlementSet.cashflow;
};

export const isExportWatermarked = (cache: EntitlementCache): boolean => {
  return !hasPaidEntitlement(cache);
};

export const getBusinessReportExportWatermark = (cache: EntitlementCache): string | null => {
  if (!isExportWatermarked(cache)) {
    return null;
  }

  return FREE_EXPORT_WATERMARK;
};
